# Generated by Django 3.2.8 on 2021-10-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField()),
                ('subscription_time', models.TimeField()),
                ('description', models.CharField(max_length=5000)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BOT1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_keys', models.IntegerField()),
                ('Secret_Keys', models.IntegerField()),
                ('Expiry_date', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('Max_loss', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BOT2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_keys', models.IntegerField()),
                ('Secret_Keys', models.IntegerField()),
                ('Expiry_date', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('Max_loss', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BOT3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_keys', models.IntegerField()),
                ('Secret_Keys', models.IntegerField()),
                ('Expiry_date', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('Max_loss', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BOT4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_keys', models.IntegerField()),
                ('Secret_Keys', models.IntegerField()),
                ('Expiry_date', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('Max_loss', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('bank', models.CharField(max_length=500)),
                ('referral', models.CharField(max_length=10)),
                ('another_referral', models.CharField(max_length=10)),
            ],
        ),
    ]
