# Generated by Django 3.2.8 on 2021-10-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot1',
            name='API_keys',
        ),
        migrations.RemoveField(
            model_name='bot1',
            name='Secret_Keys',
        ),
        migrations.RemoveField(
            model_name='bot2',
            name='API_keys',
        ),
        migrations.RemoveField(
            model_name='bot2',
            name='Secret_Keys',
        ),
        migrations.RemoveField(
            model_name='bot3',
            name='API_keys',
        ),
        migrations.RemoveField(
            model_name='bot3',
            name='Secret_Keys',
        ),
        migrations.RemoveField(
            model_name='bot4',
            name='API_keys',
        ),
        migrations.RemoveField(
            model_name='bot4',
            name='Secret_Keys',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank',
        ),
        migrations.AddField(
            model_name='bot1',
            name='binance_API_keys',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='bot1',
            name='binance_Secret_Keys',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='bot2',
            name='binance_API_keys',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='bot2',
            name='binance_Secret_Keys',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='bot3',
            name='angel_API_keys',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='bot3',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='bot3',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='bot4',
            name='angel_API_keys',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='bot4',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='bot4',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='account_num',
            field=models.IntegerField(default='999'),
        ),
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.IntegerField(default='999'),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='ifsc',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
