# Generated by Django 3.2.8 on 2021-10-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_bot_subscription_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='angel_API_keys',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='user1',
            name='angel_password',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='user1',
            name='angel_username',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='user1',
            name='binance_API_keys',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='user1',
            name='binance_Secret_Keys',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
