# Generated by Django 2.2.14 on 2021-11-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211028_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='profit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user1',
            name='security',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user1',
            name='another_referral',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user1',
            name='referral',
            field=models.IntegerField(default=0),
        ),
    ]
